services:
  - type: web
    name: ziyokor-server
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_VERSION
        value: 18

  - type: static
    name: ziyokor-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishDir: client/dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: ziyokor-server
          property: host
